defaultNamespace: cert-manager
helm:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.13.3
  releaseName: cert-manager
  values:
    installCRDs: true
    startupapicheck:
      timeout: 5m
    prometheus:
      enabled: false 