apiVersion: v1
kind: Secret
metadata:
  name: application-collection
  namespace: suse-ai
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "dp.apps.rancher.io": {
          "auth": "${REGISTRY_TOKEN}"
        }
      }
    } 