apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-test
  namespace: gpu-operator
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/cuda:11.8.0-base-ubi8
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1 